name: Deploy to Remote Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image GO"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Remote Deployment
      uses: sulthonzh/docker-remote-deployment-action@v0.1.2-beta
      with:
        remote_docker_host:  ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
        ssh_public_key: ${{ secrets.REMOTE_HOST_PUB_KEY }}
        ssh_private_key: ${{ secrets.REMOTE_SSH_KEY }}
        pull_images_first: true


    # - name: Deploy to remote server
    #   uses: appleboy/ssh-action@v0.1.4
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.REMOTE_SSH_KEY }}
    #     script: |
    #       sudo docker pull ${{ secrets.DOCKER_USERNAME }}/go-app:latest
    #       sudo docker stop go-app || true
    #       sudo docker rm go-app || true
    #       sudo docker run -d --name go-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/go-app:latest
