name: Deploy to Remote Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image GO"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Write SSH private key to file
      run: |
       echo "${{ secrets.REMOTE_SSH_KEY }}" | base64 -d > id_rsa
       chmod 600 id_rsa
       cat id_rsa

    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.1.4
      with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         key: id_rsa
         script: |
           sudo docker pull ${{ secrets.DOCKER_USERNAME }}/go-app:latest
           sudo docker stop go-app || true
           sudo docker rm go-app || true
           sudo docker run -d --name go-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/go-app:latest
