name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
    - name: Install dependencies
      run: go mod download
      working-directory: ./go-app
    - name: Lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && golangci-lint run
      working-directory: ./go-app
    - name: Test
      run: go test ./...
      working-directory: ./go-app
